services:
  s3:
    image: minio/minio:RELEASE.2020-02-07T23-28-16Z
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 9000:9000
    volumes:
      - ./test:/data
  app:
    build:
      context: .
    volumes:
      - ./src:/home/node/app/src:ro,consistent
      - ./test/local:/home/node/local
    command: -k minio -s minio123 -b bucket-1 -e http://s3:9000 -d /home/node/local -f
    ports:
      - 8080:8080
    depends_on:
      - s3
